syslog:
  build: ./syslog
  volumes:
    - /tmp/syslogdev:/dev
  expose:
    - "514"

syslogappender:
  image: ubuntu
  volumes_from:
    - syslog
  command: tail -f /var/log/syslog

elasticsearch:
  build: ./elasticsearch
  expose:
    - "9200" # http
    - "9300" # transport

logstash:
  build: ./logstash
  expose:
    - "5228" # udp
    - "5229" # tcp

  links:
    - elasticsearch

kibana:
  build: ./kibana
  links:
    - elasticsearch
  expose:
    - "5601"

haproxy:
  build: ./haproxy
  links:
      - "syslog"
      - "elasticsearch"
      - "kibana"
      - "logstash"

  volumes:
    - /tmp/syslogdev/log:/dev/log

  ports:
    - "80:80"
    - "5601:5601"
    - "5228:5228"
    - "5229:5229"
    - "9200:9200"
    - "9300:9300"
